title: Afsana Tarannum
logo: "assets/img/HEADSHOT-modified.png"
description: Doctoral Student | Urban Affairs 
theme: jekyll-theme-minimal
extra_css:
  - "assets/css/custom.css"

navigation:
  - title: Home
    slug: /
  - title: Blog
    slug: /blog
  - title: About
    slug: /company/about
  - title: Contact
    slug: /company/contact
