title: Afsana Tarannum
logo: "assets/img/WhatsApp Image 2024-12-09 at 09.25.33_e80e3bd2-modified.png"
description: Doctoral Student | Urban Affairs 
description: tarannum@memphis.edu
description: www.linkedin.com/in/afsana-tarannum
theme: jekyll-theme-minimal


