title: Afsana Tarannum
logo: "/assets/images/HEADSHOT.jpg"
description: Doctoral Student | Urban Affairs 
theme: jekyll-theme-minimal

/* assets/css/custom.css */

.circle-image {
  border-radius: 50%;
  width: 150px;  
  height: 150px; 
  object-fit: cover; 
}
extra_css:
  - "/assets/css/custom.css" 
  
