title: Afsana Tarannum
logo: "assets/img/WhatsApp Image 2024-12-09 at 09.25.33_e80e3bd2-modified.png"
description: Doctoral Student | Urban Affairs 
theme: jekyll-theme-minimal


# Social Sharing
twitter:
  username               : &twitter
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 :  # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
