title: Afsana Tarannum
logo: "assets/img/WhatsApp Image 2024-12-09 at 09.25.33_e80e3bd2-modified.png"
- tarannum@memphis.edu
- [LinkedIn](www.linkedin.com/in/afsana-tarannum)
description: Doctoral Student | Urban Affairs 
theme: jekyll-theme-minimal


